# Generated by Django 3.2.8 on 2021-10-30 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='high_bidder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='current_high_bidder', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctions',
            name='winner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='auction_winner', to='auctions.user'),
            preserve_default=False,
        ),
    ]
