# Generated by Django 3.2.8 on 2021-10-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211030_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='completed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
