# Generated by Django 3.2.8 on 2021-10-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctions_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='starting_bid',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctions',
            name='url',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
