# Generated by Django 3.2.8 on 2021-10-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bids_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
