# Generated by Django 3.2.8 on 2021-10-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auctions',
            new_name='Auction',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
