# Generated by Django 3.2.8 on 2021-10-30 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='completed',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='high_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_high_bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auction_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
