# Generated by Django 3.2.8 on 2021-10-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20211030_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item_name',
            new_name='title',
        ),
    ]
