# Generated by Django 3.2.8 on 2021-10-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='completed',
            new_name='ended',
        ),
    ]
