# Generated by Django 3.2.8 on 2021-10-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_completed_auction_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
