# Generated by Django 3.2.8 on 2021-10-31 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_auction_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='high_bidder',
        ),
        migrations.AddField(
            model_name='auction',
            name='high_bid',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='high_bid', to='auctions.bid'),
            preserve_default=False,
        ),
    ]
