# Generated by Django 3.2.8 on 2021-10-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_bid_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
