# Generated by Django 3.2.8 on 2021-12-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_user_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.TextField(blank=True, default='User did not provide a summary!', null=True),
        ),
    ]
