# Generated by Django 3.2.8 on 2021-12-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_followers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
    ]
