# Generated by Django 3.2.8 on 2021-12-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
